#!/usr/bin/env bash
# Configure a local Proof-Refactor checkout without installing system tools.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_DIR="$REPO_ROOT/config"
CONFIG_FILE="$CONFIG_DIR/default.yaml"
ENV_FILE="$REPO_ROOT/.env"
ENV_EXAMPLE="$REPO_ROOT/.env.example"

WORKSPACE="Lean"
VARIANT="light"
PROMPTS_DIR=""
API_KEY=""
BASE_URL=""
MODEL=""
LEAN_REPL=""
VALIDATE_WORKSPACE=1

usage() {
    cat <<'EOF'
Usage: bash configure.sh [options]

Options:
  --workspace PATH      Lean workspace root, relative to this checkout or absolute. Default: Lean
  --variant NAME        Prompt variant: light or plan. Default: light
  --prompts-dir PATH    Optional external prompt root override
  --api-key KEY         Write GEMINI_API_KEY to .env
  --base-url URL        Write BASE_URL to .env
  --model NAME          Write MODEL to .env
  --lean-repl VALUE     Write LEAN_REPL to .env, e.g. true or false
  --no-validate         Skip Lean workspace validation
  -h, --help            Show this help
EOF
}

fail() {
    printf 'error: %s\n' "$*" >&2
    exit 1
}

while [ "$#" -gt 0 ]; do
    case "$1" in
        --workspace)
            [ "$#" -ge 2 ] || fail "--workspace requires a value"
            WORKSPACE="$2"
            shift 2
            ;;
        --variant)
            [ "$#" -ge 2 ] || fail "--variant requires a value"
            VARIANT="$2"
            shift 2
            ;;
        --prompts-dir)
            [ "$#" -ge 2 ] || fail "--prompts-dir requires a value"
            PROMPTS_DIR="$2"
            shift 2
            ;;
        --api-key)
            [ "$#" -ge 2 ] || fail "--api-key requires a value"
            API_KEY="$2"
            shift 2
            ;;
        --base-url)
            [ "$#" -ge 2 ] || fail "--base-url requires a value"
            BASE_URL="$2"
            shift 2
            ;;
        --model)
            [ "$#" -ge 2 ] || fail "--model requires a value"
            MODEL="$2"
            shift 2
            ;;
        --lean-repl)
            [ "$#" -ge 2 ] || fail "--lean-repl requires a value"
            LEAN_REPL="$2"
            shift 2
            ;;
        --no-validate)
            VALIDATE_WORKSPACE=0
            shift
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            fail "unknown option: $1"
            ;;
    esac
done

case "$VARIANT" in
    light|plan) ;;
    *) fail "--variant must be 'light' or 'plan'" ;;
esac

if [ "$VALIDATE_WORKSPACE" -eq 1 ]; then
    WORKSPACE_CHECK="$WORKSPACE"
    case "$WORKSPACE_CHECK" in
        /*|[A-Za-z]:/*|[A-Za-z]:\\*) ;;
        *) WORKSPACE_CHECK="$REPO_ROOT/$WORKSPACE_CHECK" ;;
    esac

    [ -d "$WORKSPACE_CHECK" ] || fail "Lean workspace does not exist: $WORKSPACE"
    if [ ! -f "$WORKSPACE_CHECK/lakefile.toml" ] && [ ! -f "$WORKSPACE_CHECK/lakefile.lean" ]; then
        fail "Lean workspace is missing lakefile.toml or lakefile.lean: $WORKSPACE"
    fi
    [ -f "$WORKSPACE_CHECK/lean-toolchain" ] || fail "Lean workspace is missing lean-toolchain: $WORKSPACE"
fi

yaml_quote() {
    local value="${1//\\/\/}"
    value="${value//\'/\'\'}"
    printf "'%s'" "$value"
}

mkdir -p "$CONFIG_DIR"

{
    printf '# Local Proof-Refactor defaults generated by configure.sh.\n'
    printf '# Paths below are relative to workspace_dir unless absolute.\n\n'
    printf 'paths:\n'
    printf '  workspace_dir: %s\n' "$(yaml_quote "$WORKSPACE")"
    printf '  prompts_variant: %s\n' "$(yaml_quote "$VARIANT")"
    if [ -n "$PROMPTS_DIR" ]; then
        printf '  prompts_dir: %s\n' "$(yaml_quote "$PROMPTS_DIR")"
    fi
    printf '  output_dir: output\n'
    printf '  dataset_dir: dataset\n'
    printf '  session_logs_dir: output/session_logs\n'
} > "$CONFIG_FILE"

if [ ! -f "$ENV_FILE" ]; then
    if [ -f "$ENV_EXAMPLE" ]; then
        cp "$ENV_EXAMPLE" "$ENV_FILE"
    else
        touch "$ENV_FILE"
    fi
fi

set_env_var() {
    local key="$1"
    local value="$2"
    [ -n "$value" ] || return 0

    local escaped
    escaped="$(printf '%s' "$value" | sed -e 's/[\\&|]/\\&/g')"
    if grep -q "^${key}=" "$ENV_FILE"; then
        sed -i.bak "s|^${key}=.*|${key}=${escaped}|" "$ENV_FILE"
        rm -f "${ENV_FILE}.bak"
    else
        printf '%s=%s\n' "$key" "$value" >> "$ENV_FILE"
    fi
}

set_env_var "GEMINI_API_KEY" "$API_KEY"
set_env_var "BASE_URL" "$BASE_URL"
set_env_var "MODEL" "$MODEL"
set_env_var "LEAN_REPL" "$LEAN_REPL"

printf 'Wrote %s\n' "$CONFIG_FILE"
printf 'Ensured %s\n' "$ENV_FILE"
printf 'Next: uv run proof-refactor run dataset/repeat_test.lean\n'
